package com.flutcloud.flutlink.ui.theme

import androidx.compose.ui.graphics.Color

// FlutLink / OperationFlut brand palette (blue-violet accent hue 266, deep
// navy surfaces). Values mirror src/style.css `[data-theme="operationflut"]`.

// --- Light ---
val LightPrimary = Color(0xFF4A4FAA)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDFE0FF)
val LightOnPrimaryContainer = Color(0xFF2A2F80)
val LightSecondary = Color(0xFF5C5E8A)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE1E0FF)
val LightOnSecondaryContainer = Color(0xFF484A73)
val LightTertiary = Color(0xFF006B5E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF9DF1E0)
val LightOnTertiaryContainer = Color(0xFF00382F)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF4F4F7)
val LightOnBackground = Color(0xFF09090B)
val LightSurface = Color(0xFFF4F4F7)
val LightOnSurface = Color(0xFF09090B)
val LightSurfaceVariant = Color(0xFFE5E5EC)
val LightOnSurfaceVariant = Color(0xFF52525B)
val LightSurfaceContainer = Color(0xFFFFFFFF)
val LightSurfaceContainerHigh = Color(0xFFECECF1)
val LightSurfaceContainerHighest = Color(0xFFD7D7E0)
val LightOutline = Color(0xFFB9B9C6)
val LightOutlineVariant = Color(0xFFECECF1)

// --- Dark ---
val DarkPrimary = Color(0xFFB6C0FF)
val DarkOnPrimary = Color(0xFF1C2484)
val DarkPrimaryContainer = Color(0xFF2E3AA8)
val DarkOnPrimaryContainer = Color(0xFFDDE2FF)
val DarkSecondary = Color(0xFFC5C4FF)
val DarkOnSecondary = Color(0xFF2C2F58)
val DarkSecondaryContainer = Color(0xFF3D3F6F)
val DarkOnSecondaryContainer = Color(0xFFE1E0FF)
val DarkTertiary = Color(0xFF7DD8C6)
val DarkOnTertiary = Color(0xFF00382F)
val DarkTertiaryContainer = Color(0xFF005044)
val DarkOnTertiaryContainer = Color(0xFF9DF1E0)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF090821)
val DarkOnBackground = Color(0xFFFAFAFA)
val DarkSurface = Color(0xFF090821)
val DarkOnSurface = Color(0xFFFAFAFA)
val DarkSurfaceVariant = Color(0xFF232152)
val DarkOnSurfaceVariant = Color(0xFF9A99B3)
val DarkSurfaceContainer = Color(0xFF0D0C2B)
val DarkSurfaceContainerHigh = Color(0xFF161434)
val DarkSurfaceContainerHighest = Color(0xFF232152)
val DarkOutline = Color(0xFF3C3A6E)
val DarkOutlineVariant = Color(0xFF171530)